name: Automated API tests using Postman CLI3

on: push

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "31816131-ab428970-b970-4020-8982-bd7412cd068a" -e "31816131-235e4565-6c5e-412e-bba3-c07a18c4b08d"
